export default {
  ad1: require('./images/banner1.jpg'),
  ad2: require('./images/banner2.jpg'),
  avatar: require('./images/avatar.jpg'),
  lock1:require('./images/lock_icon.png'),
  zm: require('./images/sfz1.png'),
  bm: require('./images/sfz2.png'),
  rlsb: require('./images/rlsb.png'),
  LOCK: require('./images/lock.png'),
  UNLOCK: require('./images/unlock.png'),
  nodata: require('./images/nodata.png'),
  scanline:require('./images/scan_line.png'),
  map:require('./images/map.png'),
  error:require('./images/error_icon.png'),
  yes:require('./images/yes_icon.png'),
  loading:require('./images/loading.gif'),
}
